var characters = {
	'Melee Fox': 'fox',
	'Melee Falco': 'falco',
	'Melee Marth': 'marth',
	'Melee Sheik': 'sheik',
	'Melee Jigglypuff': 'jigglypuff',
	'Melee Peach': 'peach',
	'Melee Ice Climbers': 'ic',
	'Melee Captain Falcon': 'cf',
	'Melee Pikachu': 'pikachu',
	'Melee Samus': 'samus',
	'Melee Dr. Mario': 'doc',
	'Melee Yoshi': 'yoshi',
	'Melee Luigi': 'luigi',
	'Melee Ganondorf': 'ganondorf',
	'Melee Mario': 'mario',
	'Melee Young Link': 'yl',
	'Melee Donkey Kong': 'dk',
	'Melee Link': 'link',
	'Melee Mr. Game & Watch': 'gw',
	'Melee Roy': 'roy',
	'Melee Mewtwo': 'mewtwo',
	'Melee Zelda': 'zelda',
	'Melee Ness': 'ness',
	'Melee Pichu': 'pichu',
	'Melee Bowser': 'bowser',
	'Melee Kirby': 'kirby',
    'PM Bowser': 'pmbowser',
    'PM Captain Falcon': 'pmcf',
    'PM Charizard': 'pmzard',
    'PM DDD': 'pmddd',
    'PM Diddy Kong': 'pmdiddy',
    'PM Donkey Kong': 'pmdk',
    'PM Falco': 'pmfalco',
    'PM Fox': 'pmfox',
    'PM Gannondorf': 'pmdorf',
    'PM Ice Climbers': 'pmic',
    'PM Ike': 'pmike',
    'PM Ivysaur': 'pmivy',
    'PM Jigglypuff': 'pmjiggly',
    'PM Kirby': 'pmkirby',
    'PM Link': 'pmlink',
    'PM Lucario': 'pmlucario',
    'PM Lucas': 'pmlucas',
    'PM Luigi': 'pmluigi',
    'PM Mario': 'pmmario',
    'PM Marth': 'pmmarth',
    'PM MetaKnight': 'pmmeta',
    'PM Mewtwo': 'pmmewtwo',
    'PM G&W': 'pmgw',
    'PM Ness': 'pmness',
    'PM Olimar': 'pmolimar',
    'PM Peach': 'pmpeach',
    'PM Pikachu': 'pmpika',
    'PM Pit': 'pmpit',
    'PM ROB': 'pmrob',
    'PM Roy': 'pmroy',
    'PM Samus': 'pmsamus',
    'PM Sheik': 'pmsheik',
    'PM Snake': 'pmsnake',
    'PM Sonic': 'pmsonic',
    'PM Squirtle': 'pmsquirtle',
    'PM Toon Link': 'pmtoonl',
    'PM Wario': 'pmwario',
    'PM Wolf': 'pmwolf',
    'PM Yoshi': 'pmyoshi',
    'PM Zelda': 'pmzelda',
    'PM ZSS': 'pmzss',
    'Random': 'random',
    'S4 Bayonetta':'s4bayo',
    'S4 Bowser':'s4bowser',
    'S4 Bowser Jr':'s4bowserjr',
    'S4 Captain Falcon':'s4cf',
    'S4 Charizard':'s4zard',
    'S4 Cloud':'s4cloud',
    'S4 Corrin Girl':'s4corring',
    'S4 Dark Pit':'s4dpit',
    'S4 King Dedede':'s4ddd',
    'S4 Diddy Kong':'s4diddy',
    'S4 Donkey Kong':'s4dk',
    'S4 Dr Mario':'s4drm',
    'S4 Duck Hunt Dog':'s4dhd',
    'S4 Falco':'s4falco',
    'S4 Fox':'s4fox',
    'S4 Game and Watch':'s4gw',
    'S4 Ganondorf':'s4ganon',
    'S4 Greninja':'s4gninja',
    'S4 Ike':'s4ike',
    'S4 Jigglypuff':'s4puff',
    'S4 Kirby':'s4kirby',
    'S4 Link':'s4link',
    'S4 Little Mac':'s4mac',
    'S4 Lucario':'s4lucario',
    'S4 Lucas':'s4lucas',
    'S4 Lucina':'s4lucina',
    'S4 Luigi':'s4luigi',
    'S4 Mario':'s4mario',
    'S4 Marth':'s4marth',
    'S4 Megaman':'s4mm',
    'S4 Mii Girl':'s4miig',
    'S4 Meta Knight':'s4mk',
    'S4 Mewtwo':'s4mt',
    'S4 Ness':'s4ness',
    'S4 Olimar':'s4olimar',
    'S4 Pacman':'s4pacman',
    'S4 Palutena':'s4palu',
    'S4 Peach':'s4peach',
    'S4 Pikachu':'s4pika',
    'S4 Pit':'s4pit',
    'S4 ROB':'s4rob',
    'S4 Robin Girl':'s4robing',
    'S4 Rosalina':'s4rosa',
    'S4 Roy':'s4roy',
    'S4 Ryu':'s4ryu',
    'S4 Samus':'s4samus',
    'S4 Sheik':'s4sheik',
    'S4 Shulk':'s4shulk',
    'S4 Sonic':'s4sonic',
    'S4 Toon Link':'s4tl',
    'S4 Villager':'s4villager',
    'S4 Wario':'s4wario',
    'S4 Wii Fit Trainer Girl':'s4wftg',
    'S4 Yoshi':'s4yoshi',
    'S4 Zelda':'s4zelda',
    'S4 Zero Suit Samus':'s4wetdream'
}
